# Favicon
favicon: /favicon.ico

# SEO
keywords: books

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# Nav menu
menu:
  Home: /
  Github: https://github.com/dexhunter
  RSS: /atom.xml
